// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PawSpital.Data;

#nullable disable

namespace PawSpital.Migrations
{
    [DbContext(typeof(SpitalContext))]
    [Migration("20260430095552_InitialCreateWithSeeds")]
    partial class InitialCreateWithSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PawSpital.Models.Departament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descriere")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departamente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descriere = "Departamentul de boli cardiovasculare",
                            Nume = "Cardiologie"
                        },
                        new
                        {
                            Id = 2,
                            Descriere = "Departamentul de afectiuni neurologice",
                            Nume = "Neurologie"
                        },
                        new
                        {
                            Id = 3,
                            Descriere = "Departamentul de chirurgie ortopedica",
                            Nume = "Ortopedie"
                        },
                        new
                        {
                            Id = 4,
                            Descriere = "Departamentul pentru ingrijirea copiilor",
                            Nume = "Pediatrie"
                        },
                        new
                        {
                            Id = 5,
                            Descriere = "Departamentul de afectiuni ale pielii",
                            Nume = "Dermatologie"
                        },
                        new
                        {
                            Id = 6,
                            Descriere = "Departamentul de boli ale ochilor",
                            Nume = "Oftalmologie"
                        });
                });

            modelBuilder.Entity("PawSpital.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartamentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specializare")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentId");

                    b.ToTable("Doctori");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartamentId = 1,
                            Nume = "Dr. Andrei Popescu",
                            Specializare = "Cardiologie"
                        },
                        new
                        {
                            Id = 2,
                            DepartamentId = 2,
                            Nume = "Dr. Maria Ionescu",
                            Specializare = "Neurologie"
                        },
                        new
                        {
                            Id = 3,
                            DepartamentId = 3,
                            Nume = "Dr. Vlad Georgescu",
                            Specializare = "Ortopedie"
                        },
                        new
                        {
                            Id = 4,
                            DepartamentId = 4,
                            Nume = "Dr. Elena Dumitrescu",
                            Specializare = "Pediatrie"
                        },
                        new
                        {
                            Id = 5,
                            DepartamentId = 5,
                            Nume = "Dr. Cristian Radu",
                            Specializare = "Dermatologie"
                        },
                        new
                        {
                            Id = 6,
                            DepartamentId = 6,
                            Nume = "Dr. Ana Vasilescu",
                            Specializare = "Oftalmologie"
                        },
                        new
                        {
                            Id = 7,
                            DepartamentId = 1,
                            Nume = "Dr. Mihai Stanescu",
                            Specializare = "Cardiologie interventionala"
                        },
                        new
                        {
                            Id = 8,
                            DepartamentId = 2,
                            Nume = "Dr. Ioana Popa",
                            Specializare = "Neuropediatrie"
                        });
                });

            modelBuilder.Entity("PawSpital.Models.Programare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumePacient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SalaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiciuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("SalaId");

                    b.HasIndex("ServiciuId");

                    b.ToTable("Programari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(2026, 5, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            NumePacient = "Ion Marinescu",
                            SalaId = 1,
                            ServiciuId = 2,
                            Status = "Confirmata",
                            Telefon = "0721000001"
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(2026, 5, 6, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            NumePacient = "Ana Petrescu",
                            SalaId = 3,
                            ServiciuId = 4,
                            Status = "In asteptare",
                            Telefon = "0731000002"
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(2026, 5, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            NumePacient = "George Enescu",
                            SalaId = 2,
                            ServiciuId = 7,
                            Status = "Confirmata",
                            Telefon = "0741000003"
                        },
                        new
                        {
                            Id = 4,
                            Data = new DateTime(2026, 5, 8, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 6,
                            NumePacient = "Lucia Badea",
                            SalaId = 4,
                            ServiciuId = 8,
                            Status = "In asteptare",
                            Telefon = "0751000004"
                        });
                });

            modelBuilder.Entity("PawSpital.Models.Recenzie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentariu")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumePacient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Recenzii");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comentariu = "Doctor excelent, foarte atent cu pacientii!",
                            DoctorId = 1,
                            NumePacient = "Ion Marinescu",
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            Comentariu = "Profesionalism si rapiditate.",
                            DoctorId = 2,
                            NumePacient = "Maria Dumitru",
                            Rating = 4
                        },
                        new
                        {
                            Id = 3,
                            Comentariu = "Recomand cu incredere pentru copii.",
                            DoctorId = 4,
                            NumePacient = "George Enescu",
                            Rating = 5
                        },
                        new
                        {
                            Id = 4,
                            Comentariu = "Foarte multumita de consultatie.",
                            DoctorId = 5,
                            NumePacient = "Elena Stan",
                            Rating = 4
                        });
                });

            modelBuilder.Entity("PawSpital.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Etaj")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Salii");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Etaj = 0,
                            Nume = "Sala A1 - Consultatii"
                        },
                        new
                        {
                            Id = 2,
                            Etaj = 0,
                            Nume = "Sala A2 - Consultatii"
                        },
                        new
                        {
                            Id = 3,
                            Etaj = 1,
                            Nume = "Sala B1 - Investigatii"
                        },
                        new
                        {
                            Id = 4,
                            Etaj = 1,
                            Nume = "Sala B2 - Imagistica"
                        },
                        new
                        {
                            Id = 5,
                            Etaj = 2,
                            Nume = "Sala C1 - Operatii"
                        },
                        new
                        {
                            Id = 6,
                            Etaj = 2,
                            Nume = "Sala C2 - Recuperare"
                        });
                });

            modelBuilder.Entity("PawSpital.Models.Serviciu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descriere")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Pret")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servicii");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descriere = "Consultatie medicala de baza",
                            Nume = "Consultatie generala",
                            Pret = 150.00m
                        },
                        new
                        {
                            Id = 2,
                            Descriere = "Ecografie Doppler a inimii",
                            Nume = "Ecografie cardiaca",
                            Pret = 350.00m
                        },
                        new
                        {
                            Id = 3,
                            Descriere = "Electrocardiograma standard",
                            Nume = "EKG",
                            Pret = 120.00m
                        },
                        new
                        {
                            Id = 4,
                            Descriere = "Rezonanta magnetica nucleara craniu",
                            Nume = "RMN cerebral",
                            Pret = 800.00m
                        },
                        new
                        {
                            Id = 5,
                            Descriere = "Radiografie standard",
                            Nume = "Radiografie",
                            Pret = 100.00m
                        },
                        new
                        {
                            Id = 6,
                            Descriere = "Hemoleucograma completa",
                            Nume = "Analiza de sange completa",
                            Pret = 200.00m
                        },
                        new
                        {
                            Id = 7,
                            Descriere = "Consultatie specializata copii",
                            Nume = "Consultatie pediatrica",
                            Pret = 180.00m
                        },
                        new
                        {
                            Id = 8,
                            Descriere = "Examen complet al vederii",
                            Nume = "Examen oftalmologic",
                            Pret = 250.00m
                        });
                });

            modelBuilder.Entity("PawSpital.Models.Doctor", b =>
                {
                    b.HasOne("PawSpital.Models.Departament", "Departament")
                        .WithMany("Doctori")
                        .HasForeignKey("DepartamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departament");
                });

            modelBuilder.Entity("PawSpital.Models.Programare", b =>
                {
                    b.HasOne("PawSpital.Models.Doctor", "Doctor")
                        .WithMany("Programari")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PawSpital.Models.Sala", "Sala")
                        .WithMany("Programari")
                        .HasForeignKey("SalaId");

                    b.HasOne("PawSpital.Models.Serviciu", "Serviciu")
                        .WithMany()
                        .HasForeignKey("ServiciuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Sala");

                    b.Navigation("Serviciu");
                });

            modelBuilder.Entity("PawSpital.Models.Recenzie", b =>
                {
                    b.HasOne("PawSpital.Models.Doctor", "Doctor")
                        .WithMany("Recenzii")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("PawSpital.Models.Departament", b =>
                {
                    b.Navigation("Doctori");
                });

            modelBuilder.Entity("PawSpital.Models.Doctor", b =>
                {
                    b.Navigation("Programari");

                    b.Navigation("Recenzii");
                });

            modelBuilder.Entity("PawSpital.Models.Sala", b =>
                {
                    b.Navigation("Programari");
                });
#pragma warning restore 612, 618
        }
    }
}
